[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
line_length = 160
skip_gitignore = true
# https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html
multi_line_output = 3
reverse_relative = true
use_parentheses = true
combine_star = true
force_grid_wrap = 2
include_trailing_comma = true
