#!/bin/sh
APP="$1"
ENV="$2"
DOCKER_COMPOSE_FILE="$3"
HUB_VOLUME=hub_data
CONF="$(readlink -f "$(dirname "$0")/../confs/hub")"
docker run --rm -i \
  -v $HUB_VOLUME:/hub:rw \
  -v $CONF:/conf:ro \
  python:3.8 \
  python /conf/post_deploy "$APP" "$ENV" "$DOCKER_COMPOSE_FILE" /hub/data/apps.json
