#!/bin/sh
APP="$1"
ENV="$2"
CONF="$(readlink -f "$(dirname "$0")/../confs/monitoring")"
GRAFANA_VOLUME=monitoring-prod_grafana_conf
GRAFANA_DATA=$(docker inspect $GRAFANA_VOLUME 2>/dev/null|jq -r '.[0].Mountpoint')
if [ "$GRAFANA_DATA" = "null" ]; then
  exit 0
fi
python3 $CONF/post_deploy "$APP" "$ENV" "$GRAFANA_DATA"
