#!/bin/sh
APP="$1"
ENV="$2"
DCF="$3"
HUB_VOLUME=hub-volume # TO CHANGE
CONF="$(readlink -f "$(dirname "$0")/../confs/hub")"
docker run --rm -i \
  -v $HUB_VOLUME:/hub:rw \
  -v $CONF:/conf:ro \
  python:3.7 \
  python /conf/pre_undeploy "$APP" "$ENV" "$DCF" /hub/data/apps.json
